##Import Library

In [1]:
import pandas as pd
import numpy as np

##Bikin list berisi link ke repository JSON

In [2]:
# for i in range (3000):
#   variabel = str(i)
#   link = "http://repository.lppm.unila.ac.id/cgi/exportview/year/"+variabel+"/JSON/"+variabel+".js"
#   print(link)

# df = pd.read_json()

In [3]:
tahun = ['NULL','0015','0016','0017','0020','0021','0022','0028','0029','0200','0201','0202','0207','0214','0220','0223','1010','1977',
         '1985','1990','1991','1992','1992','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005',
         '2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023',
         '2107','3018']
links = []

for i in range(len(tahun)):
  variabel = str(tahun[i])
  link = "http://repository.lppm.unila.ac.id/cgi/exportview/year/"+variabel+"/JSON/"+variabel+".js"
  links.append(link)
  print(links[i])

http://repository.lppm.unila.ac.id/cgi/exportview/year/NULL/JSON/NULL.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0015/JSON/0015.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0016/JSON/0016.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0017/JSON/0017.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0020/JSON/0020.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0021/JSON/0021.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0022/JSON/0022.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0028/JSON/0028.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0029/JSON/0029.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0200/JSON/0200.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0201/JSON/0201.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0202/JSON/0202.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0207/JSON/0207.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0214/JSON/0214.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0220/JSON/0220.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/0223/JSON/0223.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1010/JSON/1010.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1977/JSON/1977.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1985/JSON/1985.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1990/JSON/1990.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1991/JSON/1991.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1992/JSON/1992.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1992/JSON/1992.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1993/JSON/1993.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1994/JSON/1994.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1995/JSON/1995.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1996/JSON/1996.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1997/JSON/1997.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1998/JSON/1998.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/1999/JSON/1999.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2000/JSON/2000.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2001/JSON/2001.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2002/JSON/2002.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2003/JSON/2003.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2004/JSON/2004.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2005/JSON/2005.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2006/JSON/2006.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2007/JSON/2007.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2008/JSON/2008.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2009/JSON/2009.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2010/JSON/2010.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2011/JSON/2011.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2012/JSON/2012.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2013/JSON/2013.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2014/JSON/2014.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2015/JSON/2015.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2016/JSON/2016.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2017/JSON/2017.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2018/JSON/2018.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2019/JSON/2019.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2020/JSON/2020.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2021/JSON/2021.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2022/JSON/2022.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2023/JSON/2023.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/2107/JSON/2107.js
http://repository.lppm.unila.ac.id/cgi/exportview/year/3018/JSON/3018.js

##Buat dataset dari repository

Masing-masing repository digabung jadi 1 dataset besar dengan nama "hasil"

In [4]:
# df = []
# df.append(pd.read_json("http://repository.lppm.unila.ac.id/cgi/exportview/year/3018/JSON/3018.js"))
# df.append(pd.read_json("http://repository.lppm.unila.ac.id/cgi/exportview/year/2107/JSON/2107.js"))
# hasil = pd.concat(df)
# hasil

df = []
for i in range(len(links)):
  df.append(pd.read_json(links[i]))

hasil = pd.concat(df)

##Hasil dari dataset

In [5]:
hasil.head()

,ispublished,contributors,documents,publisher,uri,full_text_status,refereed,lastmod,userid,pagerange,...,note,data_type,composition_type,task_purpose,date,patent_applicant,thesis_name,thesis_type,copyright_holders,learning_level
0,pub,"[{'name': {'lineage': None, 'honourific': None...","[{'format': 'text', 'pos': 1, 'rev_number': 1,...",CV. Media Sains Indonesia,http://repository.lppm.unila.ac.id/id/eprint/5...,public,TRUE,2023-04-25 11:24:42,18893,1-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pub,NaN,[{'files': [{'hash': 'a1f34b61014d950bacca9fb6...,Aura Publishing,http://repository.lppm.unila.ac.id/id/eprint/5...,public,TRUE,2023-04-12 07:41:28,1026,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,pub,NaN,"[{'docid': 190088, 'main': 'KEWENANGAN KEJAKSA...",Aura Publishing,http://repository.lppm.unila.ac.id/id/eprint/5...,public,TRUE,2023-04-12 07:41:33,1026,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pub,NaN,"[{'placement': 1, 'security': 'public', 'eprin...",SAI WAWAI PUBLISHING,http://repository.lppm.unila.ac.id/id/eprint/5...,public,TRUE,2023-05-12 09:29:13,1026,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pub,NaN,"[{'files': [{'datasetid': 'document', 'filesiz...",Indepth Publishing,http://repository.lppm.unila.ac.id/id/eprint/5...,public,TRUE,2023-04-12 07:41:38,1026,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
hasil.describe()

             userid    rev_number      eprintid      succeeds         pages
count  37375.000000  37375.000000  37375.000000   1057.000000  1.315000e+03
mean     919.392776      7.539023  27436.861565  25314.202460  1.086359e+06
std     1930.505061      1.968288  15043.576882  13682.092057  3.932554e+07
min        1.000000      3.000000      4.000000    525.000000  0.000000e+00
25%      387.000000      6.000000  14621.500000  14655.000000  3.600000e+01
50%      696.000000      7.000000  28226.000000  26127.000000  1.120000e+02
75%      950.000000      8.000000  40560.500000  36693.000000  1.900000e+02
max    26496.000000     49.000000  52428.000000  52019.000000  1.426061e+09

In [7]:
hasil.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37375 entries, 0 to 0
Data columns (total 66 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ispublished          37349 non-null  object
 1   contributors         4255 non-null   object
 2   documents            36894 non-null  object
 3   publisher            29400 non-null  object
 4   uri                  37375 non-null  object
 5   full_text_status     37375 non-null  object
 6   refereed             24918 non-null  object
 7   lastmod              37375 non-null  object
 8   userid               37375 non-null  int64
 9   pagerange            16505 non-null  object
 10  datestamp            37375 non-null  object
 11  dir                  37375 non-null  object
 12  type                 37375 non-null  object
 13  editors              345 non-null    object
 14  book_title           822 non-null    object
 15  divisions            32865 non-null  object
 16  title                37375 non-null  object
 17  rev_number           37375 non-null  int64
 18  metadata_visibility  37375 non-null  object
 19  status_changed       37375 non-null  object
 20  eprint_status        37375 non-null  object
 21  subjects             37357 non-null  object
 22  eprintid             37375 non-null  int64
 23  date_type            22969 non-null  object
 24  isbn                 1119 non-null   object
 25  abstract             29247 non-null  object
 26  place_of_pub         2479 non-null   object
 27  creators             37352 non-null  object
 28  corp_creators        7554 non-null   object
 29  official_url         16398 non-null  object
 30  publication          18694 non-null  object
 31  issn                 16057 non-null  object
 32  contact_email        3199 non-null   object
 33  number               14139 non-null  object
 34  id_number            5828 non-null   object
 35  volume               14985 non-null  object
 36  related_url          6043 non-null   object
 37  referencetext        1662 non-null   object
 38  keywords             900 non-null    object
 39  event_type           4709 non-null   object
 40  event_dates          3951 non-null   object
 41  event_location       4121 non-null   object
 42  event_title          4705 non-null   object
 43  pres_type            4722 non-null   object
 44  completion_time      11 non-null     object
 45  funders              1224 non-null   object
 46  pedagogic_type       15 non-null     object
 47  skill_areas          10 non-null     object
 48  monograph_type       374 non-null    object
 49  succeeds             1057 non-null   float64
 50  pages                1315 non-null   float64
 51  institution          310 non-null    object
 52  department           267 non-null    object
 53  series               184 non-null    object
 54  projects             709 non-null    object
 55  output_media         79 non-null     object
 56  note                 135 non-null    object
 57  data_type            16 non-null     object
 58  composition_type     4 non-null      object
 59  task_purpose         6 non-null      object
 60  date                 28946 non-null  object
 61  patent_applicant     649 non-null    object
 62  thesis_name          88 non-null     object
 63  thesis_type          88 non-null     object
 64  copyright_holders    8 non-null      object
 65  learning_level       8 non-null      object
dtypes: float64(2), int64(3), object(61)
memory usage: 19.1+ MB

##Mengambil kolom yang diperlukan
Data yang perlu di ambil meliputi division, title, abstract, subjects, publication, publisher, date, keywords

In [8]:
hasil_df = hasil[['divisions','title','abstract','subjects','publication','publisher','date','keywords']]

In [9]:
hasil_df.head()

,divisions,title,abstract,subjects,publication,publisher,date,keywords
0,[FKIP23],ANAK DAN TANTANGAN MASA KINI,NaN,[LB1501],NaN,CV. Media Sains Indonesia,NaN,NaN
1,NaN,Jalan Sunyi Sang Guru,NaN,[K1],NaN,Aura Publishing,NaN,NaN
2,NaN,Kewenangan Kejaksaan dalam Penyidikan dan Prap...,NaN,[K1],NaN,Aura Publishing,NaN,NaN
3,NaN,MEMBANGUN PARADIGMA KEMARITIMAN INDONESIA,NaN,[K1],NaN,SAI WAWAI PUBLISHING,NaN,NaN
4,NaN,PENDAFTARAN TANAH HAK ULAYAT MASYARAKAT HUKUM ...,NaN,[K1],NaN,Indepth Publishing,NaN,NaN

##Jadikan CSV

In [13]:
hasil_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37375 entries, 0 to 0
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   divisions    32865 non-null  object
 1   title        37375 non-null  object
 2   abstract     29247 non-null  object
 3   subjects     37357 non-null  object
 4   publication  18694 non-null  object
 5   publisher    29400 non-null  object
 6   date         28946 non-null  object
 7   keywords     900 non-null    object
dtypes: object(8)
memory usage: 2.6+ MB

In [14]:
#File akan disimpan dalam bentuk out.csv di dalam out.zip
compression_opts = dict(method='zip',archive_name='out.csv')
hasil_df.to_csv('out.zip', index=False,compression=compression_opts)